[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "mime"
    version = "1.0.0"
    path = "../mime-native/build/libs/mime-native-1.0.1-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["mime"]

    [[platform.libraries]]
    artifactId = "mimepull"
    version = "1.9.11"
    path = "./lib/mimepull-1.9.7.jar"
    groupId = "org.jvnet.mimepull"
    modules = ["mime"]

    [[platform.libraries]]
    artifactId = "commons-pool"
    version = "1.5.6.wso2v1"
    path = "./lib/commons-pool-1.5.6.wso2v1.jar"
    groupId = "commons-pool.wso2"
    modules = ["mime"]

    [[platform.libraries]]
    artifactId = "snakeyaml"
    version = "1.16.0.wso2v1"
    path = "./lib/snakeyaml-1.16.0.wso2v1.jar"
    groupId = "org.wso2.orbit.org.yaml"
    modules = ["mime"]

    [[platform.libraries]]
    artifactId = "bcprov-jdk15on"
    version = "1.61"
    path = "./lib/bcprov-jdk15on-1.61.jar"
    groupId = "org.bouncycastle"
    modules = ["mime"]

    [[platform.libraries]]
    artifactId = "bcpkix-jdk15on"
    version = "1.61"
    path = "./lib/bcpkix-jdk15on-1.61.jar"
    groupId = "org.bouncycastle"
    modules = ["mime"]
