[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "mime"
    version = "@project.version@"
    path = "../mime-native/build/libs/mime-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["mime"]

    [[platform.libraries]]
    artifactId = "mimepull"
    version = "@project.mimepullVersion@"
    path = "./lib/mimepull-@project.mimepullVersion@.jar"
    groupId = "org.jvnet.mimepull"
    modules = ["mime"]

