[package]
org = "ballerina"
name = "mime"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "io"
version = "@stdlib.io.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "stringutils"
version = "@stdlib.stringutils.version@"

[[platform.java11.dependency]]
path = "../mime-native/build/libs/mime-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "mime"
version = "@project.version@"


[[platform.java11.dependency]]
path = "./lib/mimepull-@mimepull.version@.jar"
groupId = "org.jvnet.mimepull"
artifactId = "mimepull"
version = "@mimepull.version@"


[[platform.java11.dependency]]
path = "./lib/jakarta.activation-@jakarta.activation.version@.jar"
groupId = "com.sun.activation"
artifactId = "jakarta.activation"
version = "@jakarta.activation.version@"
