[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/io" = "@stdlib.io.version@"
"ballerina/log" = "@stdlib.log.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "mime"
    version = "@project.version@"
    path = "../mime-native/build/libs/mime-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["mime"]

    [[platform.libraries]]
    artifactId = "mimepull"
    version = "@mimepull.version@"
    path = "./lib/mimepull-@mimepull.version@.jar"
    groupId = "org.jvnet.mimepull"
    modules = ["mime"]

    [[platform.libraries]]
    artifactId = "jakarta.activation"
    version = "@jakarta.activation.version@"
    path = "./lib/jakarta.activation-@jakarta.activation.version@.jar"
    groupId = "com.sun.activation"
    modules = ["mime"]
