[package]
org = "ballerina"
name = "mime"
version = "1.0.2"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.5.2"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.0.2"

[[dependency]]
org = "ballerina"
name = "stringutils"
version = "0.5.2"

[[platform.java11.dependency]]
path = "../mime-native/build/libs/mime-native-1.0.2-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "mime"
version = "1.0.2-SNAPSHOT"


[[platform.java11.dependency]]
path = "./lib/mimepull-1.9.11.jar"
groupId = "org.jvnet.mimepull"
artifactId = "mimepull"
version = "1.9.11"


[[platform.java11.dependency]]
path = "./lib/jakarta.activation-1.2.2.jar"
groupId = "com.sun.activation"
artifactId = "jakarta.activation"
version = "1.2.2"
